workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20
      groups:
        - google_play
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Expo prebuild
        script: |
          npx expo prebuild --platform android --clean
      - name: Build Android AAB
        script: |
          cd android && ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@gmail.com
